#
###################################
# Site wide configuration
####################################
#
title: XguoX
email: xguox@hotmail.com
description: Ruby Golang Erlang 前端 后端 Android Elasticsearch Programmer Photo Lens Camera Sony A7r Fujifilm Lego
url: https://xguox.me # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          China/Beijing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: XguoX
  avatar: logo.jpeg
  job: "写点 Ruby 糊口饭吃"
  bio: "Model 42082"
  email: xguox@hotmail.com
  disqus-shortname: xguox
  twitter: xguox_l #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62252083-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: xguox #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: groverlu
  codepen: #username
